### ISSUE TITLE
Wpml Support

### ISSUE THREAD

**Issue by phscam** [towa-digital/towa-gdpr-plugin#24]
**Describe the bug**
If the Wpml multilingual plugin is active there is no synchronisation of the hash between languages.
Because of that the cookie notice gets displayed everytime the user changes the language (as every language has a different hash and the local browser cookie gets overwritten with this specific hash for the active language)

**To Reproduce**
1. Go to a website that uses towa-gdpr-plugin in sitepress-multilingual-cms
2. Change between languages -> you have to accept the cookies every time you change the language

**Expected behavior**
As a User I want to accept the cookie notice once and not every time I change the language.
As an Admin I want to synchronise the hash between languages (possible fix: make the acf hash field editable and enable manual synchronisation between languages with that - copy paste between languages)

**Desktop**
 - OS: independent
 - Browser independent
 - Version v1.1.8

**Smartphone**
 - Device: independent
 - OS: independent
 - Browser independent
 - Version v1.1.8

**Comment by Martin-Welte** [comment]
@phscam this behaviour is actually intended. Since different trackers can be active in different languages - it is neccessary to display two different cookie notices, if you have two languages active. However, I think is that we could save the hash once per language instead of overwriting the same value - which ultimately would solve the issue of constantly having to accept it if you switch a buch of times. Having to do it once per language would still persist though.

**Comment by SahinU88** [comment]
We will stop the maintenance of this in the near future, thus we don't look at requests.

Sry for this one.
